---
title: "R Notebook"
output: html_notebook
---

Script of how to find missing data in the study. 


```{r}
library(papaja)
library(tidyverse)
library(dplyr)
```

```{r}
#Creating the filtered dataframe 
pilot.df <- read.csv("combined_pilot_batches.csv", na=c("")) %>%
  filter(!(word %in% c('', 'ZEBRA'))) %>%
  mutate(subj_id=PROLIFIC_PID)
pilot.df

data_from_games <- pilot.df %>%
  filter(trial_type=='Hangman_replay') %>%
  dplyr::select(subj_id,word,num_clicks) 
data_from_games

data_from_confidence <- read.csv("combined_pilot_batches.csv") %>%
  mutate(subj_id=PROLIFIC_PID,
         confidence=as.numeric(confidence_slider_self_response)) %>%
  group_by(subj_id) %>%
  summarise(
    confidence=mean(confidence,na.rm=T)
  )
data_from_confidence

data_from_guesses <- pilot.df %>%
  filter(trial_type=='Guess_leaderboard') %>%
  dplyr::select(subj_id,subject_pair,word,position,position_RT,true_position,reveal_word,player,distance, self_rating)
data_from_guesses

#Merge above to new usable, filtered dataframe
filtered_df <- data_from_games %>%
  merge(data_from_guesses) %>%
  merge(data_from_confidence)
filtered_df

#Change variables from characters to correct classification 
#Change reveal_word into a categorical variable
filtered_df$reveal_word <- factor(filtered_df$reveal_word)
#Change position into an integer variable 
filtered_df$position <- as.integer(filtered_df$position)
#Change true_position into an integer variable
filtered_df$true_position <- as.integer(filtered_df$true_position)
#Change distance into an integer variable 
filtered_df$distance <- as.integer(filtered_df$distance)
#Change self-rating into an integer
filtered_df$self_rating <- as.integer(filtered_df$self_rating)
#Change word into a categorical variable 
filtered_df$word <- factor(filtered_df$word)

#Check variables were changed correctly
#Check class reveal_word
class(filtered_df$reveal_word)
#Check class position 
class(filtered_df$position)
#Check class true position 
class(filtered_df$true_position)
#check class distance 
class(filtered_df$distance)
#check class self rating
class(filtered_df$self_rating)
#check class word 
class(filtered_df$word)


#Rename levels of reveal_word from true and false to revealed and hidden, respectively 
filtered_df$reveal_word <- factor(filtered_df$reveal_word, levels = c("true", "false"), labels = c("revealed", "hidden"))

# Check the levels of reveal_word variable
levels(filtered_df$reveal_word)

#Check changes in filtered_df (whcih we will be using for our analysis)
print(filtered_df)
```


```{r}
missing_check <- filtered_df %>% group_by(subject_pair) %>%summarise(nrevealed=length(unique(subj_id[reveal_word=='revealed'])),nhidden=length(unique(subj_id[reveal_word=='hidden'])))
missing_check
```



