---
title: "Bayesian T-Tests"
output: html_notebook
---

LOAD PACKAGES

```{r setup, include = FALSE}
library('groundhog')
groundhog.library(
  c(
    'papaja', #for apa formatting
    'pwr', # for power calculation
    'tidyverse', # for pipe %>%
    'emmeans',
    'afex',
    'patchwork',
    'officer',
    'cowplot',
    'ggrepel',
    'dplyr',
    'BayesFactor'
  ), "2024-04-09"
)

knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, results='hide')
```

LOAD DATA 

```{r}
pilot.df <- read.csv("combined_pilot_batches.csv", na=c("")) %>%
  filter(!(word %in% c('', 'ZEBRA'))) %>%
  mutate(subj_id=PROLIFIC_PID)
pilot.df
```


# PREPARE DATAFRAMES

```{r}
data_from_games <- pilot.df %>%
  filter(trial_type=='Hangman_replay') %>%
  dplyr::select(subj_id,word,num_clicks) 
data_from_games

data_from_confidence <- read.csv("combined_pilot_batches.csv") %>%
  mutate(subj_id=PROLIFIC_PID,
         confidence=as.numeric(confidence_slider_self_response)) %>%
  group_by(subj_id) %>%
  summarise(
    confidence=mean(confidence,na.rm=T)
  )
data_from_confidence

data_from_guesses <- pilot.df %>%
  filter(trial_type=='Guess_leaderboard') %>%
  dplyr::select(subj_id,subject_pair,word,position,position_RT,true_position,reveal_word,player,distance, self_rating)
data_from_guesses
          
#Merge above to new usable, filtered dataframe
filtered_df <- data_from_games %>%
  merge(data_from_guesses) %>%
  merge(data_from_confidence)
filtered_df

#Change variables from characters to correct classification 
#Change reveal_word into a categorical variable
filtered_df$reveal_word <- factor(filtered_df$reveal_word)
#Change position into an integer variable 
filtered_df$position <- as.integer(filtered_df$position)
#Change true_position into an integer variable
filtered_df$true_position <- as.integer(filtered_df$true_position)
#Change distance into an integer variable 
filtered_df$distance <- as.integer(filtered_df$distance)
#Change self-rating into an integer
filtered_df$self_rating <- as.integer(filtered_df$self_rating)
#Change word into a categorical variable 
filtered_df$word <- factor(filtered_df$word)
#Change distance into an integer variable 
filtered_df$distance <- as.integer(filtered_df$distance)
#change confidence into an integer variable
filtered_df$confidence <- as.integer(filtered_df$confidence)

#Check variables were changed correctly
#Check class reveal_word
class(filtered_df$reveal_word)
#Check class position 
class(filtered_df$position)
#Check class true position 
class(filtered_df$true_position)
#check class distance 
class(filtered_df$distance)
#check class self rating
class(filtered_df$self_rating)
#check class word 
class(filtered_df$word)
#check class distance 
class(filtered_df$distance)
#check class confidence
class(filtered_df$confidence)

#Rename levels of reveal_word from true and false to revealed and hidden, respectively 
filtered_df$reveal_word <- factor(filtered_df$reveal_word, levels = c("true", "false"), labels = c("revealed", "hidden"))

# Check the levels of reveal_word variable
levels(filtered_df$reveal_word)

#Check changes in filtered_df (which we will be using for our analysis)
print(filtered_df)
```

```{r create-paired-df}
#Create Paired dataset for analysis
hidden_df <- filtered_df %>%
  filter(reveal_word=='hidden') 

revealed_df <- filtered_df %>%
  filter(reveal_word=='revealed') 

paired_df <- hidden_df %>%
  merge(revealed_df, by=c('subject_pair','word','player','true_position','num_clicks'),
        suffixes=c('.hidden','.revealed'))
paired_df
```

```{r}
#Createdmean paired dataframe for position and self-rating analysis 
mean_df <- paired_df %>%
  group_by(subject_pair)%>%
  summarise(self_rating.hidden=mean(self_rating.hidden),
            self_rating.revealed=mean(self_rating.revealed),
            position.hidden=mean(position.hidden),
            position.revealed=mean(position.revealed),
            confidence.hidden=mean(confidence.hidden),
            confidence.revealed=mean(confidence.revealed),
            distance.hidden=mean(distance.hidden),
            distance.revealed=mean(distance.revealed))%>%
  mutate(self_rating.diff=self_rating.hidden-self_rating.revealed,
         position.diff=position.hidden-position.revealed,
         confidence.diff=confidence.hidden-confidence.revealed,
         distance.diff=distance.hidden-distance.revealed)
mean_df
```



#### Bayesian T-Tests

Run a Bayesian t-test on null results to test if we have evidence for the null.


Position

```{r}
# paired t-test
t_test_bf_position_pair <- ttestBF(x = mean_df$position.hidden, y = mean_df$position.revealed, paired = TRUE)
t_test_bf_position_pair
```


Self-rating

```{r}
# paired t-test
t_test_bf_self_rating_pair <- ttestBF(x = mean_df$self_rating.hidden, y = mean_df$self_rating.revealed, paired = TRUE)
t_test_bf_self_rating_pair
```

Confidence

```{r}
# paired t-test
t_test_bf_confidence_pair <- ttestBF(x = mean_df$confidence.hidden, y = mean_df$confidence.revealed, paired = TRUE)
t_test_bf_confidence_pair
```


Accuracy 

```{r}
# paired t-test
t_test_bf_accuracy_pair <- ttestBF(x = mean_df$distance.hidden, y = mean_df$distance.revealed, paired = TRUE)
t_test_bf_accuracy_pair
```
