---
title: "Predicted position Guess by Word"
output: html_notebook
---

Predicted position guess by word - plot

LOAD PACKAGES

```{r setup, include = FALSE}
library('groundhog')
groundhog.library(
  c(
    'papaja', #for apa formatting
    'pwr', # for power calculation
    'tidyverse', # for pipe %>%
    'emmeans',
    'afex',
    'patchwork',
    'officer',
    'cowplot',
    'ggrepel',
    'dplyr',
    'BayesFactor'
  ), "2024-04-09"
)

knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, results='hide')
```


CREATE DATAFRAMES

```{r}
pilot.df <- read.csv("combined_pilot_batches.csv", na=c("")) %>%
  filter(!(word %in% c('', 'ZEBRA'))) %>%
  mutate(subj_id=PROLIFIC_PID)
pilot.df
```


# Prepare all the dataframes

```{r}
data_from_games <- pilot.df %>%
  filter(trial_type=='Hangman_replay') %>%
  dplyr::select(subj_id,word,num_clicks) 
data_from_games

data_from_confidence <- read.csv("combined_pilot_batches.csv") %>%
  mutate(subj_id=PROLIFIC_PID,
         confidence=as.numeric(confidence_slider_self_response)) %>%
  group_by(subj_id) %>%
  summarise(
    confidence=mean(confidence,na.rm=T)
  )
data_from_confidence

data_from_guesses <- pilot.df %>%
  filter(trial_type=='Guess_leaderboard') %>%
  dplyr::select(subj_id,subject_pair,word,position,position_RT,true_position,reveal_word,player,distance, self_rating)
data_from_guesses
          
#Merge above to new usable, filtered dataframe
filtered_df <- data_from_games %>%
  merge(data_from_guesses) %>%
  merge(data_from_confidence)
filtered_df

#Change variables from characters to correct classification 
#Change reveal_word into a categorical variable
filtered_df$reveal_word <- factor(filtered_df$reveal_word)
#Change position into an integer variable 
filtered_df$position <- as.integer(filtered_df$position)
#Change true_position into an integer variable
filtered_df$true_position <- as.integer(filtered_df$true_position)
#Change distance into an integer variable 
filtered_df$distance <- as.integer(filtered_df$distance)
#Change self-rating into an integer
filtered_df$self_rating <- as.integer(filtered_df$self_rating)
#Change word into a categorical variable 
filtered_df$word <- factor(filtered_df$word)
#Change distance into an integer variable 
filtered_df$distance <- as.integer(filtered_df$distance)
#change confidence into an integer variable
filtered_df$confidence <- as.integer(filtered_df$confidence)

#Check variables were changed correctly
#Check class reveal_word
class(filtered_df$reveal_word)
#Check class position 
class(filtered_df$position)
#Check class true position 
class(filtered_df$true_position)
#check class distance 
class(filtered_df$distance)
#check class self rating
class(filtered_df$self_rating)
#check class word 
class(filtered_df$word)
#check class distance 
class(filtered_df$distance)
#check class confidence
class(filtered_df$confidence)

#Rename levels of reveal_word from true and false to revealed and hidden, respectively 
filtered_df$reveal_word <- factor(filtered_df$reveal_word, levels = c("true", "false"), labels = c("revealed", "hidden"))

# Check the levels of reveal_word variable
levels(filtered_df$reveal_word)

#Check changes in filtered_df (which we will be using for our analysis)
print(filtered_df)
```

```{r create-paired-df}
#Create Paired dataset for analysis
hidden_df <- filtered_df %>%
  filter(reveal_word=='hidden') 

revealed_df <- filtered_df %>%
  filter(reveal_word=='revealed') 

paired_df <- hidden_df %>%
  merge(revealed_df, by=c('subject_pair','word','player','true_position','num_clicks'),
        suffixes=c('.hidden','.revealed'))
paired_df
```

CREATE PLOT 

Position by word by condition scatterplot

```{r}
position_by_word <- paired_df %>%
  group_by(word)%>%
  summarise(position.hidden=mean(position.hidden),
            position.revealed=mean(position.revealed))

paired_df %>%
  ggplot(aes(x = position.hidden, y = position.revealed, color = word, label = word)) +
  geom_abline(slope = 1, intercept = 0, color = "black", linetype = "dashed") + # Main diagonal line
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_point(data = position_by_word, size = 2, show.legend = FALSE) +
  geom_label_repel(data = position_by_word, show.legend = FALSE) +
  theme_classic() +
  scale_y_reverse(name = 'Position Guess, Revealed', breaks = c(1, 25, 50, 75, 100)) +
  scale_x_reverse(name = 'Position Guess, Hidden', breaks = c(1, 25, 50, 75, 100)) +
  coord_fixed(ratio = 1) + # Ensures the plot is square
  theme(aspect.ratio = 1) +
  labs(title = "Pairwise Predicted Position Ranking")

ggsave(file="Exploratory_plots/pairsWordsScatterSquare.png")
```



